const CONFIG = {
    titleWeb: "WelcomeTo2022",
    introTitle: 'Haloooo Mẹppppp 🥰',
    introDesc: ` Cám ơn đã làm việc chăm chỉ, đã mạnh mẽ cố gắng suốt năm qua~ 
2021 có gì mịt mỏi pùn phiền gì thì bỏ lại ùi cùm nhau sang năm mới thôuuu🎉`,
    btnIntro: '^^LetsGoooo^^',
    title: '2021 của Mẹp như thế nàoo?🥺',
    desc: 'Điều gì trong năm 2021 tuỵt nhất đem lại choa Mẹp dzaa??🤓',
    btnYes: 'Là NH chứ còn gì nữaaaa<33',
    btnNo: 'Không có gì đặc biệt :3',
    question: ' Nào nhắmm mắt 3 giây suy nghĩ òyy ghi những đìu ước mong muốn cho 2022 nàaaa 🧚🏻‍♀️💕',
    btnReply: '🌟Send It🍀',
    reply: 'Dù hong bít B đã ước gì nhưng mong có thể cố gắng và thực hiện nó cùm nhau^^',
    mess: 'TengTengg🥳 Thế là baibai 2021 ùii👋 ',
    messDesc: ' Mới đây mừ nch lại vs b hơn nửa năm òyy~🤭 Nhanh vaizz^^ Trch chưa baoh nghĩ là nch, gặp lại b vậy mà bâyh nó dãy nè:)))) quả là hong gì đoán trc đc nhuôn mèee🤣♥️',
    btnAccept: '♥️',
